function ItemDetails() {
  this.items = [{
    name: 'High',
    description: 'Artwork',
    active: false
  }, {
    name: 'Low',
    description: 'Word',
    active: false
  }, {
    name: 'Right',
    description: 'Powerpoint',
    active: false
  }, {
    name: 'Left',
    description: 'Excel',
    active: false
  }, {
    name: 'High1',
    description: 'Image',
    active: false
  }, {
    name: 'Low1',
    description: 'PDF',
    active: false
  }, {
    name: 'Right1',
    description: 'Video',
    active: false
  }, {
    name: 'Left1',
    description: 'Powerpoint',
    active: false
  }, {
    name: 'High2',
    description: 'Video',
    active: false
  }, {
    name: 'Low2',
    description: 'PDF',
    active: false
  }, {
    name: 'Right2',
    description: 'Excel',
    active: false
  }, {
    name: 'Left2',
    description: 'Word',
    active: false
  }]
}